apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-usb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/usb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-usb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi